homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: admin_dashboard_personnel
        permanent: false

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
